unit TestUValorTotal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UValorTotal;

type
  // Test methods for class TPedido

  TestTPedido = class(TTestCase)
  strict private
    FPedido: TPedido;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalcularValorTotal;
  end;

implementation

procedure TestTPedido.SetUp;
begin
  FPedido := TPedido.Create;
end;

procedure TestTPedido.TearDown;
begin
  FPedido.Free;
  FPedido := nil;
end;

procedure TestTPedido.TestCalcularValorTotal;
var
  ReturnValue: Double;
  aPreco: Double;
  aQuantidade: Integer;
begin
  aPreco      := 10;
  aQuantidade := 10;

  ReturnValue := FPedido.CalcularValorTotal(aQuantidade, aPreco);
  CheckEquals(100, ReturnValue, 'Erro em sem desconto');

  aPreco      := 10;
  aQuantidade := 20;

  ReturnValue := FPedido.CalcularValorTotal(aQuantidade, aPreco);
  CheckEquals(180, ReturnValue, 'Erro no Desconto de 10%');

  aPreco      := 10;
  aQuantidade := 100;

  ReturnValue := FPedido.CalcularValorTotal(aQuantidade, aPreco);
  CheckEquals(750, ReturnValue, 'Erro no Desconto de 25%');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPedido.Suite);
end.

